Repository asiffermann/proffer, pull requests merged in 2021-05, with the labels that each got.

#41 Integration tests
  .github/workflows/dotnet.yml
  .gitignore
  Proffer.sln
  README.md
  coverlet.runsettings
  src/Proffer.Email.SendGrid/Proffer.Email.SendGrid.csproj
  src/Proffer.Email.Smtp/Proffer.Email.Smtp.csproj
  src/Proffer.Email/Options/EmailOptions.cs
  src/Proffer.Email/ServiceCollectionExtensions.cs
  src/Proffer.Storage.Azure/AzureStore.cs
  src/Proffer.Storage.Azure/Internal/AzureFileProperties.cs
  src/Proffer.Storage.Azure/Internal/AzureFileReference.cs
  src/Proffer.Storage.Azure/Internal/AzureListDirectoryWrapper.cs
  src/Proffer.Storage.Azure/Internal/AzureListFileWrapper.cs
  src/Proffer.Storage.Azure/Proffer.Storage.Azure.csproj
  src/Proffer.Storage.FileSystem/FileSystemStore.cs
  src/Proffer.Storage/Configuration/StorageOptions.cs
  src/Proffer.Storage/IStore.cs
  src/Proffer.Storage/Internal/ConfigureProviderOptions.cs
  src/Proffer.Storage/Internal/GenericStoreProxy.cs
  tests/Proffer.Email.SendGrid.Tests/Proffer.Email.SendGrid.Tests.csproj
  tests/Proffer.Email.SendGrid.Tests/SendGridCollection.cs
  tests/Proffer.Email.SendGrid.Tests/SendGridFixture.cs
  tests/Proffer.Email.SendGrid.Tests/SendSimpleEmailTests.cs
  tests/Proffer.Email.SendGrid.Tests/SendTemplatedEmailTests.cs
  tests/Proffer.Email.SendGrid.Tests/Stores/Attachments/beach.jpeg
  tests/Proffer.Email.SendGrid.Tests/Stores/Attachments/sample.pdf
  tests/Proffer.Email.SendGrid.Tests/Stores/Templates/Notification1-BodyHtml.hbs
  tests/Proffer.Email.SendGrid.Tests/Stores/Templates/Notification1-BodyText.hbs
  tests/Proffer.Email.SendGrid.Tests/Stores/Templates/Notification1-Subject.hbs
  tests/Proffer.Email.SendGrid.Tests/appsettings.json
  tests/Proffer.Storage.Azure.Tests/AzureCollection.cs
  tests/Proffer.Storage.Azure.Tests/AzureFixture.cs
  tests/Proffer.Storage.Azure.Tests/DeleteTests.cs
  tests/Proffer.Storage.Azure.Tests/GenericStoreTests.cs
  tests/Proffer.Storage.Azure.Tests/GetScopedStoreTests.cs
  tests/Proffer.Storage.Azure.Tests/GetSharedAccessSignatureTests.cs
  tests/Proffer.Storage.Azure.Tests/ListTests.cs
  tests/Proffer.Storage.Azure.Tests/Proffer.Storage.Azure.Tests.csproj
  tests/Proffer.Storage.Azure.Tests/ReadTests.cs
  tests/Proffer.Storage.Azure.Tests/SaveTests.cs
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/Delete/ToDelete.txt
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/Delete/ToSurvive.txt
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/Globbing/template-header.hbs
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/Globbing/template-header.mustache
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/Globbing/template.hbs
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/Globbing/template.mustache
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/Metadata/TextFile.txt
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/SubDirectory/TextFile2.txt
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/TextFile.txt
  tests/Proffer.Storage.Azure.Tests/Stores/DefaultContent/template.hbs
  tests/Proffer.Storage.Azure.Tests/Stubs/StoreOptionsStub.cs
  tests/Proffer.Storage.Azure.Tests/appsettings.json
  tests/Proffer.Testing/GenericExtensions.cs
  tests/Proffer.Testing/Proffer.Testing.csproj
  tests/Proffer.Testing/ServiceProviderCollection{TFixture}.cs
  tests/Proffer.Testing/ServiceProviderFixture.cs
Labels: dependencies, quality

#51 CI/CD enhancements
  .github/Dependabot.yml
  .github/workflows/dotnet.yml
  .github/workflows/third-party-tests-results.yml
  .gitignore
  Proffer.sln
  src/Proffer.Email.Smtp/Proffer.Email.Smtp.csproj
  tests/Proffer.Testing/Proffer.Testing.csproj
Labels: ci/cd, dependencies, quality

#52 GitHub Actions workflows
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/dotnet.yml
  .github/workflows/external-pr-tests-results.yml
  .github/workflows/releases.yml
  .github/workflows/third-party-tests-results.yml
  Proffer.sln
  README.md
Labels: ci/cd, dependencies, documentation

#54 GitHub Actions workflows fixes
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/external-pr-tests-results.yml
  .github/workflows/releases.yml
Labels: bug, ci/cd

#58 Fix workflows
  .github/workflows/continuous-integration.yml
  .github/workflows/releases.yml
  Proffer.sln
Labels: bug, ci/cd

#61 Deactivate branch filter for external PRs tests results workflow
  .github/workflows/external-pr-tests-results.yml
Labels: bug, ci/cd

#63 Fixes external PR tests results
  .github/workflows/continuous-integration.yml
  .github/workflows/external-pr-tests-results.yml
  gitversion.yml
Labels: bug, ci/cd

#64 Revert custom build status for unit tests job
  .github/workflows/continuous-integration.yml
Labels: bug, ci/cd

#67 GitHub Actions small fixes
  .github/workflows/continuous-deployment.yml
  .github/workflows/releases.yml
Labels: bug, ci/cd

#71 Adjust releases workflow
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/external-pr-tests-results.yml
  .github/workflows/releases.yml
Labels: bug, ci/cd

#73 Fix deploy conditions
  .github/workflows/continuous-deployment.yml
Labels: bug, ci/cd

#74 Fix NuGet.org deploy condition
  .github/workflows/continuous-deployment.yml
Labels: bug, ci/cd

#108 Safely extract host from email address
  src/Proffer.Email/Internal/EmailSender.cs
  tests/Proffer.Email.Tests/EmailSenderTests.cs
Labels: enhancement

#109 Init default FolderName when resolving untyped options
  src/Proffer.Storage/Configuration/ConfigurationExtensions.cs
  tests/Proffer.Storage.Tests/StorageConfigurationTests.cs
Labels: bug

#113 Reduce dependabot schedule interval
  .github/dependabot.yml
  src/Proffer.Storage/Configuration/ConfigurationExtensions.cs
  tests/Proffer.Storage.Tests/appsettings.json
Labels: ci/cd, dependencies
